"""Stable errors owned by the workflow engine."""

from __future__ import annotations

from enum import StrEnum


class WorkflowErrorCode(StrEnum):
    WORKFLOW_DEFINITION_INVALID = "WORKFLOW_DEFINITION_INVALID"
    WORKFLOW_DEFINITION_CONFLICT = "WORKFLOW_DEFINITION_CONFLICT"
    WORKFLOW_NOT_FOUND = "WORKFLOW_NOT_FOUND"
    WORKFLOW_COMMAND_DUPLICATE = "WORKFLOW_COMMAND_DUPLICATE"
    WORKFLOW_INVALID_TRANSITION = "WORKFLOW_INVALID_TRANSITION"
    WORKFLOW_CONCURRENCY_CONFLICT = "WORKFLOW_CONCURRENCY_CONFLICT"
    WORKFLOW_STEP_FAILED = "WORKFLOW_STEP_FAILED"
    WORKFLOW_REWORK_LIMIT_EXCEEDED = "WORKFLOW_REWORK_LIMIT_EXCEEDED"
    WORKFLOW_RECONCILIATION_FAILED = "WORKFLOW_RECONCILIATION_FAILED"
    APPROVAL_NOT_FOUND = "APPROVAL_NOT_FOUND"
    APPROVAL_ALREADY_RESOLVED = "APPROVAL_ALREADY_RESOLVED"
    APPROVAL_STALE = "APPROVAL_STALE"
    APPROVAL_UNAUTHORIZED = "APPROVAL_UNAUTHORIZED"
    APPROVAL_INVALID_REWORK_TARGET = "APPROVAL_INVALID_REWORK_TARGET"


class WorkflowError(RuntimeError):
    def __init__(self, code: WorkflowErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code
