"""Stable Item Registry and Usage Ledger errors."""

from enum import StrEnum


class RegistryErrorCode(StrEnum):
    ITEM_NOT_FOUND = "ITEM_NOT_FOUND"
    ITEM_REVISION_NOT_FOUND = "ITEM_REVISION_NOT_FOUND"
    ITEM_REVISION_CONFLICT = "ITEM_REVISION_CONFLICT"
    ITEM_REVISION_IMMUTABLE = "ITEM_REVISION_IMMUTABLE"
    ITEM_REVISION_NOT_APPROVED = "ITEM_REVISION_NOT_APPROVED"
    ITEM_COMPONENT_INVALID = "ITEM_COMPONENT_INVALID"
    ITEM_COMPONENT_DUPLICATE = "ITEM_COMPONENT_DUPLICATE"
    ITEM_MANIFEST_INVALID = "ITEM_MANIFEST_INVALID"
    ITEM_REGISTRATION_FAILED = "ITEM_REGISTRATION_FAILED"
    ITEM_REGISTRATION_DUPLICATE = "ITEM_REGISTRATION_DUPLICATE"
    ITEM_RELATIONSHIP_INVALID = "ITEM_RELATIONSHIP_INVALID"
    DELIVERABLE_NOT_FOUND = "DELIVERABLE_NOT_FOUND"
    DELIVERABLE_REVISION_NOT_FOUND = "DELIVERABLE_REVISION_NOT_FOUND"
    DELIVERABLE_REVISION_IMMUTABLE = "DELIVERABLE_REVISION_IMMUTABLE"
    USAGE_PLAN_NOT_FOUND = "USAGE_PLAN_NOT_FOUND"
    USAGE_PLAN_CONFLICT = "USAGE_PLAN_CONFLICT"
    USAGE_PLAN_ALREADY_FULFILLED = "USAGE_PLAN_ALREADY_FULFILLED"
    USAGE_RECORD_CONFLICT = "USAGE_RECORD_CONFLICT"
    USAGE_RECORD_IMMUTABLE = "USAGE_RECORD_IMMUTABLE"
    USAGE_ITEM_NOT_APPROVED = "USAGE_ITEM_NOT_APPROVED"
    CATALOG_QUERY_INVALID = "CATALOG_QUERY_INVALID"
    CATALOG_CURSOR_INVALID = "CATALOG_CURSOR_INVALID"
    CATALOG_EXPORT_FAILED = "CATALOG_EXPORT_FAILED"
    CATALOG_CONCURRENCY_CONFLICT = "CATALOG_CONCURRENCY_CONFLICT"


class RegistryError(RuntimeError):
    def __init__(self, code: RegistryErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code
