"""Stable content intake error taxonomy."""

from enum import StrEnum


class IntakeErrorCode(StrEnum):
    CONTENT_INTAKE_NOT_FOUND = "CONTENT_INTAKE_NOT_FOUND"
    CONTENT_INTAKE_INVALID = "CONTENT_INTAKE_INVALID"
    CONTENT_INTAKE_UNSAFE_PATH = "CONTENT_INTAKE_UNSAFE_PATH"
    CONTENT_INTAKE_FILE_MISSING = "CONTENT_INTAKE_FILE_MISSING"
    CONTENT_INTAKE_HASH_MISMATCH = "CONTENT_INTAKE_HASH_MISMATCH"
    CONTENT_INTAKE_SECRET_DETECTED = "CONTENT_INTAKE_SECRET_DETECTED"
    CONTENT_INTAKE_ANALYSIS_MISSING = "CONTENT_INTAKE_ANALYSIS_MISSING"
    CONTENT_INTAKE_ANALYSIS_INVALID = "CONTENT_INTAKE_ANALYSIS_INVALID"
    CONTENT_INTAKE_DECISION_REQUIRED = "CONTENT_INTAKE_DECISION_REQUIRED"
    CONTENT_INTAKE_NOT_ACCEPTED = "CONTENT_INTAKE_NOT_ACCEPTED"
    CONTENT_INTAKE_IMMUTABLE = "CONTENT_INTAKE_IMMUTABLE"
    CONTENT_INTAKE_SUPERSEDED = "CONTENT_INTAKE_SUPERSEDED"


class IntakeError(RuntimeError):
    def __init__(self, code: IntakeErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code
