"""Stable error taxonomy for the observability boundary."""

from enum import StrEnum


class ObserveErrorCode(StrEnum):
    OBSERVE_CONFIG_INVALID = "OBSERVE_CONFIG_INVALID"
    OBSERVE_SECRET_MISSING = "OBSERVE_SECRET_MISSING"
    OBSERVE_AUTH_FAILED = "OBSERVE_AUTH_FAILED"
    OBSERVE_SESSION_INVALID = "OBSERVE_SESSION_INVALID"
    OBSERVE_RATE_LIMITED = "OBSERVE_RATE_LIMITED"
    OBSERVE_DATABASE_UNAVAILABLE = "OBSERVE_DATABASE_UNAVAILABLE"
    OBSERVE_DATABASE_TIMEOUT = "OBSERVE_DATABASE_TIMEOUT"
    OBSERVE_DATABASE_NOT_READONLY = "OBSERVE_DATABASE_NOT_READONLY"
    OBSERVE_QUERY_FAILED = "OBSERVE_QUERY_FAILED"
    OBSERVE_SNAPSHOT_FAILED = "OBSERVE_SNAPSHOT_FAILED"
    OBSERVE_EVENT_MAPPING_FAILED = "OBSERVE_EVENT_MAPPING_FAILED"
    OBSERVE_REDACTION_FAILED = "OBSERVE_REDACTION_FAILED"
    OBSERVE_SCHEMA_VALIDATION_FAILED = "OBSERVE_SCHEMA_VALIDATION_FAILED"
    OBSERVE_STREAM_LIMIT_REACHED = "OBSERVE_STREAM_LIMIT_REACHED"
    OBSERVE_STREAM_DISCONNECTED = "OBSERVE_STREAM_DISCONNECTED"
    OBSERVE_CLIENT_SLOW = "OBSERVE_CLIENT_SLOW"
    OBSERVE_SYSTEM_PROBE_FAILED = "OBSERVE_SYSTEM_PROBE_FAILED"
    OBSERVE_SERVICE_MISCONFIGURED = "OBSERVE_SERVICE_MISCONFIGURED"


class ObserveError(RuntimeError):
    def __init__(self, code: ObserveErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code
