"""Stable Content Pack error taxonomy."""

from enum import StrEnum


class ContentPackErrorCode(StrEnum):
    CONTENT_PACK_INVALID = "CONTENT_PACK_INVALID"
    CONTENT_PACK_UNSAFE_PATH = "CONTENT_PACK_UNSAFE_PATH"
    CONTENT_PACK_DUPLICATE_PATH = "CONTENT_PACK_DUPLICATE_PATH"
    CONTENT_PACK_SECRET_DETECTED = "CONTENT_PACK_SECRET_DETECTED"
    CONTENT_PACK_REFERENCE_MISSING = "CONTENT_PACK_REFERENCE_MISSING"
    CONTENT_PACK_SCHEMA_INVALID = "CONTENT_PACK_SCHEMA_INVALID"
    CONTENT_PACK_PROFILE_INVALID = "CONTENT_PACK_PROFILE_INVALID"
    CONTENT_PACK_TEMPLATE_INVALID = "CONTENT_PACK_TEMPLATE_INVALID"
    CONTENT_PACK_BUILD_FAILED = "CONTENT_PACK_BUILD_FAILED"
    CONTENT_PACK_HASH_CONFLICT = "CONTENT_PACK_HASH_CONFLICT"
    CONTENT_PACK_COMPATIBILITY_FAILED = "CONTENT_PACK_COMPATIBILITY_FAILED"
    CONTENT_PACK_NOT_RELEASED = "CONTENT_PACK_NOT_RELEASED"
    CONTENT_PACK_RELEASE_IMMUTABLE = "CONTENT_PACK_RELEASE_IMMUTABLE"
    CONTENT_PACK_ACTIVATION_CONFLICT = "CONTENT_PACK_ACTIVATION_CONFLICT"


class ContentPackError(RuntimeError):
    def __init__(self, code: ContentPackErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code
