"""add operator identity and api security state

Revision ID: 20260817_0006
Revises: 20260817_0005
Create Date: 2026-08-17 17:37:53.411240
"""

from collections.abc import Sequence
from hashlib import sha256

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260817_0006"
down_revision: str | Sequence[str] | None = "20260817_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PERMISSIONS = (
    "system:read",
    "system:doctor",
    "operator:read",
    "operator:create",
    "operator:assign_role",
    "operator:revoke_role",
    "operator:disable",
    "operator:enable",
    "operator:revoke_sessions",
    "content_intake:read",
    "content_intake:create",
    "content_intake:attach_analysis",
    "content_intake:decide",
    "content_pack:read",
    "content_pack:release",
    "content_pack:activate",
    "content_pack:deprecate",
    "workflow:read",
    "workflow:start",
    "workflow:approve",
    "workflow:request_rework",
    "workflow:cancel",
    "workflow:reconcile",
    "item:read",
    "item:retire",
    "deliverable:read",
    "deliverable:create",
    "deliverable:update",
    "usage:read",
    "usage:create_plan",
    "usage:reserve_plan",
    "usage:cancel_plan",
    "usage:fulfill_plan",
    "event:read",
)
VIEWER = frozenset(
    {
        "system:read",
        "content_intake:read",
        "content_pack:read",
        "workflow:read",
        "item:read",
        "deliverable:read",
        "usage:read",
        "event:read",
    }
)
ROLE_PERMISSIONS = {
    "VIEWER": VIEWER,
    "AUTHOR": VIEWER
    | {"content_intake:create", "content_intake:attach_analysis", "workflow:start"},
    "REVIEWER": VIEWER | {"content_intake:decide", "workflow:approve", "workflow:request_rework"},
    "EDITOR": VIEWER
    | {
        "deliverable:create",
        "deliverable:update",
        "usage:create_plan",
        "usage:reserve_plan",
        "usage:cancel_plan",
        "usage:fulfill_plan",
    },
    "ADMIN": frozenset(PERMISSIONS),
}


def _stable_id(prefix: str, key: str) -> str:
    return prefix + sha256(f"eom-api-v1:{prefix}:{key}".encode()).hexdigest()[:32]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operators",
        sa.Column("operator_id", sa.String(length=41), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("normalized_username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("role_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_by", sa.String(length=128), nullable=True),
        sa.Column("disable_reason", sa.Text(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.CheckConstraint("status IN ('ACTIVE','DISABLED')", name="ck_operators_status"),
        sa.PrimaryKeyConstraint("operator_id"),
        sa.UniqueConstraint("normalized_username"),
    )
    op.create_index("ix_operators_keyset", "operators", ["created_at", "operator_id"], unique=False)
    op.create_index("ix_operators_status", "operators", ["status"], unique=False)
    op.create_table(
        "permissions",
        sa.Column("permission_id", sa.String(length=43), nullable=False),
        sa.Column("permission_key", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("permission_id"),
        sa.UniqueConstraint("permission_key"),
    )
    op.create_table(
        "roles",
        sa.Column("role_id", sa.String(length=37), nullable=False),
        sa.Column("role_key", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("built_in", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("role_id"),
        sa.UniqueConstraint("role_key"),
    )
    op.create_table(
        "api_idempotency_records",
        sa.Column("api_idempotency_record_id", sa.String(length=40), nullable=False),
        sa.Column("operator_id", sa.String(length=41), nullable=False),
        sa.Column("endpoint_key", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key_hash", sa.String(length=71), nullable=False),
        sa.Column("request_sha256", sa.String(length=71), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('PROCESSING','COMPLETED','FAILED_FINAL')", name="ck_api_idempotency_state"
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operators.operator_id"],
        ),
        sa.PrimaryKeyConstraint("api_idempotency_record_id"),
        sa.UniqueConstraint(
            "operator_id", "endpoint_key", "idempotency_key_hash", name="uq_api_idempotency_claim"
        ),
    )
    op.create_index(
        "ix_api_idempotency_expires", "api_idempotency_records", ["expires_at"], unique=False
    )
    op.create_table(
        "api_sessions",
        sa.Column("api_session_id", sa.String(length=43), nullable=False),
        sa.Column("operator_id", sa.String(length=41), nullable=False),
        sa.Column("token_family_id", sa.String(length=44), nullable=False),
        sa.Column("client_name", sa.String(length=128), nullable=False),
        sa.Column("authenticated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(length=128), nullable=True),
        sa.Column("revoke_reason", sa.String(length=500), nullable=True),
        sa.Column("refresh_generation", sa.Integer(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operators.operator_id"],
        ),
        sa.PrimaryKeyConstraint("api_session_id"),
        sa.UniqueConstraint("token_family_id", name="uq_api_sessions_token_family"),
    )
    op.create_index(
        "ix_api_sessions_idle_expires", "api_sessions", ["idle_expires_at"], unique=False
    )
    op.create_index(
        "ix_api_sessions_operator_revoked",
        "api_sessions",
        ["operator_id", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "operator_credentials",
        sa.Column("operator_credential_id", sa.String(length=39), nullable=False),
        sa.Column("operator_id", sa.String(length=41), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("password_algorithm", sa.String(length=32), nullable=False),
        sa.Column("password_version", sa.Integer(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("first_failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operators.operator_id"],
        ),
        sa.PrimaryKeyConstraint("operator_credential_id"),
        sa.UniqueConstraint("operator_id"),
    )
    op.create_table(
        "operator_events",
        sa.Column("operator_event_id", sa.String(length=40), nullable=False),
        sa.Column("operator_id", sa.String(length=41), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operators.operator_id"],
        ),
        sa.PrimaryKeyConstraint("operator_event_id"),
        sa.UniqueConstraint("operator_id", "sequence", name="uq_operator_event_sequence"),
    )
    op.create_index(
        "ix_operator_events_keyset",
        "operator_events",
        ["created_at", "operator_event_id"],
        unique=False,
    )
    op.create_table(
        "operator_role_assignments",
        sa.Column("operator_role_assignment_id", sa.String(length=43), nullable=False),
        sa.Column("operator_id", sa.String(length=41), nullable=False),
        sa.Column("role_id", sa.String(length=37), nullable=False),
        sa.Column("assigned_by", sa.String(length=128), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_by", sa.String(length=128), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoke_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operators.operator_id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.role_id"],
        ),
        sa.PrimaryKeyConstraint("operator_role_assignment_id"),
    )
    op.create_index(
        "ix_operator_role_active_lookup",
        "operator_role_assignments",
        ["operator_id", "revoked_at"],
        unique=False,
    )
    op.create_index(
        "uq_operator_active_role",
        "operator_role_assignments",
        ["operator_id", "role_id"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.String(length=37), nullable=False),
        sa.Column("permission_id", sa.String(length=43), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.permission_id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.role_id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    role_table = sa.table(
        "roles",
        sa.column("role_id", sa.String),
        sa.column("role_key", sa.String),
        sa.column("display_name", sa.String),
        sa.column("description", sa.String),
        sa.column("built_in", sa.Boolean),
    )
    permission_table = sa.table(
        "permissions",
        sa.column("permission_id", sa.String),
        sa.column("permission_key", sa.String),
        sa.column("description", sa.String),
    )
    role_permission_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.String),
        sa.column("permission_id", sa.String),
    )
    op.bulk_insert(
        role_table,
        [
            {
                "role_id": _stable_id("role_", role_key),
                "role_key": role_key,
                "display_name": role_key.title(),
                "description": f"Built-in {role_key} role",
                "built_in": True,
            }
            for role_key in ROLE_PERMISSIONS
        ],
    )
    op.bulk_insert(
        permission_table,
        [
            {
                "permission_id": _stable_id("permission_", permission),
                "permission_key": permission,
                "description": f"Allows {permission}",
            }
            for permission in PERMISSIONS
        ],
    )
    op.bulk_insert(
        role_permission_table,
        [
            {
                "role_id": _stable_id("role_", role_key),
                "permission_id": _stable_id("permission_", permission),
            }
            for role_key, permissions in ROLE_PERMISSIONS.items()
            for permission in sorted(permissions)
        ],
    )
    op.execute(
        """
        CREATE FUNCTION app.reject_identity_key_change() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'built-in identity key is immutable';
        END;
        $$;
        CREATE TRIGGER roles_key_immutable
          BEFORE UPDATE OF role_key ON app.roles
          FOR EACH ROW WHEN (OLD.role_key IS DISTINCT FROM NEW.role_key)
          EXECUTE FUNCTION app.reject_identity_key_change();
        CREATE TRIGGER permissions_key_immutable
          BEFORE UPDATE OF permission_key ON app.permissions
          FOR EACH ROW WHEN (OLD.permission_key IS DISTINCT FROM NEW.permission_key)
          EXECUTE FUNCTION app.reject_identity_key_change();
        """
    )
    op.create_table(
        "api_audit_events",
        sa.Column("api_audit_event_id", sa.String(length=41), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("operator_id", sa.String(length=41), nullable=True),
        sa.Column("api_session_id", sa.String(length=43), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("operation_id", sa.String(length=128), nullable=False),
        sa.Column("http_method", sa.String(length=16), nullable=False),
        sa.Column("route_template", sa.String(length=256), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.String(length=128), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("client_name", sa.String(length=128), nullable=True),
        sa.Column("source_address_hash", sa.String(length=71), nullable=True),
        sa.Column("user_agent_hash", sa.String(length=71), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_session_id"],
            ["api_sessions.api_session_id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operators.operator_id"],
        ),
        sa.PrimaryKeyConstraint("api_audit_event_id"),
    )
    op.create_index(
        "ix_api_audit_created",
        "api_audit_events",
        ["created_at", "api_audit_event_id"],
        unique=False,
    )
    op.create_index(
        "ix_api_audit_operator_created",
        "api_audit_events",
        ["operator_id", "created_at"],
        unique=False,
    )
    op.execute(
        """
        CREATE FUNCTION app.reject_api_audit_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'api audit events are append-only';
        END;
        $$;
        CREATE TRIGGER api_audit_events_append_only
          BEFORE UPDATE OR DELETE ON app.api_audit_events
          FOR EACH ROW EXECUTE FUNCTION app.reject_api_audit_mutation();
        """
    )
    op.create_table(
        "api_tokens",
        sa.Column("api_token_id", sa.String(length=41), nullable=False),
        sa.Column("api_session_id", sa.String(length=43), nullable=False),
        sa.Column("token_type", sa.String(length=16), nullable=False),
        sa.Column("selector", sa.String(length=64), nullable=False),
        sa.Column("verifier_hash", sa.String(length=71), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_token_id", sa.String(length=41), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("token_type IN ('ACCESS','REFRESH')", name="ck_api_tokens_type"),
        sa.ForeignKeyConstraint(
            ["api_session_id"],
            ["api_sessions.api_session_id"],
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_token_id"],
            ["api_tokens.api_token_id"],
        ),
        sa.PrimaryKeyConstraint("api_token_id"),
        sa.UniqueConstraint("selector"),
        sa.UniqueConstraint("verifier_hash"),
    )
    op.create_index("ix_api_tokens_expires_at", "api_tokens", ["expires_at"], unique=False)
    op.create_index(
        "ix_api_tokens_session_type", "api_tokens", ["api_session_id", "token_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM app.operators) THEN
            RAISE EXCEPTION 'refusing identity downgrade while Operator data exists';
          END IF;
        END;
        $$;
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_api_tokens_session_type", table_name="api_tokens")
    op.drop_index("ix_api_tokens_expires_at", table_name="api_tokens")
    op.drop_table("api_tokens")
    op.drop_index("ix_api_audit_operator_created", table_name="api_audit_events")
    op.drop_index("ix_api_audit_created", table_name="api_audit_events")
    op.execute("DROP TRIGGER api_audit_events_append_only ON app.api_audit_events")
    op.execute("DROP FUNCTION app.reject_api_audit_mutation()")
    op.drop_table("api_audit_events")
    op.drop_table("role_permissions")
    op.execute("DROP TRIGGER permissions_key_immutable ON app.permissions")
    op.execute("DROP TRIGGER roles_key_immutable ON app.roles")
    op.execute("DROP FUNCTION app.reject_identity_key_change()")
    op.drop_index(
        "uq_operator_active_role",
        table_name="operator_role_assignments",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index("ix_operator_role_active_lookup", table_name="operator_role_assignments")
    op.drop_table("operator_role_assignments")
    op.drop_index("ix_operator_events_keyset", table_name="operator_events")
    op.drop_table("operator_events")
    op.drop_table("operator_credentials")
    op.drop_index("ix_api_sessions_operator_revoked", table_name="api_sessions")
    op.drop_index("ix_api_sessions_idle_expires", table_name="api_sessions")
    op.drop_table("api_sessions")
    op.drop_index("ix_api_idempotency_expires", table_name="api_idempotency_records")
    op.drop_table("api_idempotency_records")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_index("ix_operators_status", table_name="operators")
    op.drop_index("ix_operators_keyset", table_name="operators")
    op.drop_table("operators")
    # ### end Alembic commands ###
