"""add immutable education graph snapshots

Revision ID: 20260824_0013
Revises: 20260824_0012
Create Date: 2026-08-24 02:38:57.727638
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260824_0013"
down_revision: str | Sequence[str] | None = "20260824_0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_corpora",
        sa.Column("corpus_id", sa.String(length=39), nullable=False),
        sa.Column("corpus_key", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("graph_id", sa.String(length=38), nullable=False),
        sa.Column("current_corpus_revision_id", sa.String(length=42), nullable=True),
        sa.Column("current_graph_snapshot_revision_id", sa.String(length=41), nullable=True),
        sa.Column("lifecycle_state", sa.String(length=16), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("created_by_operator_id", sa.String(length=41), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lifecycle_state IN ('ACTIVE','RETIRED')", name="ck_knowledge_corpus_state"
        ),
        sa.CheckConstraint("lock_version >= 1", name="ck_knowledge_corpus_lock_version"),
        sa.ForeignKeyConstraint(
            ["created_by_operator_id"], ["operators.operator_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("corpus_id"),
        sa.UniqueConstraint("corpus_key"),
        sa.UniqueConstraint("graph_id"),
    )
    op.create_table(
        "knowledge_corpus_revisions",
        sa.Column("corpus_revision_id", sa.String(length=42), nullable=False),
        sa.Column("corpus_id", sa.String(length=39), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("previous_corpus_revision_id", sa.String(length=42), nullable=True),
        sa.Column("source_set_sha256", sa.String(length=71), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("created_by_operator_id", sa.String(length=41), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source_set_sha256 ~ '^sha256:[0-9a-f]{64}$'", name="ck_knowledge_corpus_revision_hash"
        ),
        sa.CheckConstraint("state = 'PUBLISHED'", name="ck_knowledge_corpus_revision_state"),
        sa.CheckConstraint("revision_number >= 1", name="ck_knowledge_corpus_revision_number"),
        sa.ForeignKeyConstraint(
            ["corpus_id"], ["knowledge_corpora.corpus_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["created_by_operator_id"], ["operators.operator_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["previous_corpus_revision_id"],
            ["knowledge_corpus_revisions.corpus_revision_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("corpus_revision_id"),
        sa.UniqueConstraint("corpus_id", "revision_number", name="uq_knowledge_corpus_revision"),
    )
    op.create_index(
        op.f("ix_knowledge_corpus_revisions_corpus_id"),
        "knowledge_corpus_revisions",
        ["corpus_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_graph_snapshots",
        sa.Column("graph_snapshot_revision_id", sa.String(length=41), nullable=False),
        sa.Column("graph_id", sa.String(length=38), nullable=False),
        sa.Column("corpus_revision_id", sa.String(length=42), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("previous_graph_snapshot_revision_id", sa.String(length=41), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("ontology_version", sa.String(length=64), nullable=False),
        sa.Column("publisher_version", sa.String(length=32), nullable=False),
        sa.Column("manifest_artifact_id", sa.String(length=41), nullable=False),
        sa.Column("manifest_artifact_revision_id", sa.String(length=36), nullable=False),
        sa.Column("projection_artifact_id", sa.String(length=41), nullable=False),
        sa.Column("projection_artifact_revision_id", sa.String(length=36), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=71), nullable=False),
        sa.Column("snapshot_sha256", sa.String(length=71), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("node_count", sa.Integer(), nullable=False),
        sa.Column("edge_count", sa.Integer(), nullable=False),
        sa.Column("anchor_count", sa.Integer(), nullable=False),
        sa.Column("created_by_operator_id", sa.String(length=41), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "snapshot_sha256 ~ '^sha256:[0-9a-f]{64}$' "
            "AND manifest_sha256 ~ '^sha256:[0-9a-f]{64}$'",
            name="ck_knowledge_graph_snapshot_hashes",
        ),
        sa.CheckConstraint("state = 'PUBLISHED'", name="ck_knowledge_graph_snapshot_state"),
        sa.CheckConstraint("revision_number >= 1", name="ck_knowledge_graph_revision_number"),
        sa.CheckConstraint(
            "source_count >= 1 AND node_count >= 1 AND edge_count >= 0 AND anchor_count >= 1",
            name="ck_knowledge_graph_snapshot_counts",
        ),
        sa.ForeignKeyConstraint(
            ["corpus_revision_id"],
            ["knowledge_corpus_revisions.corpus_revision_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_operator_id"], ["operators.operator_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["graph_id"], ["knowledge_corpora.graph_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["manifest_artifact_id"], ["artifacts.logical_artifact_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["manifest_artifact_revision_id"],
            ["artifact_revisions.revision_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["previous_graph_snapshot_revision_id"],
            ["knowledge_graph_snapshots.graph_snapshot_revision_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["projection_artifact_id"], ["artifacts.logical_artifact_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["projection_artifact_revision_id"],
            ["artifact_revisions.revision_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("graph_snapshot_revision_id"),
        sa.UniqueConstraint("corpus_revision_id", name="uq_knowledge_graph_corpus_revision"),
        sa.UniqueConstraint("graph_id", "revision_number", name="uq_knowledge_graph_revision"),
        sa.UniqueConstraint("manifest_sha256"),
    )
    op.create_index(
        "ix_knowledge_graph_snapshot_created",
        "knowledge_graph_snapshots",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_graph_snapshots_graph_id"),
        "knowledge_graph_snapshots",
        ["graph_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_knowledge_corpus_current_revision",
        "knowledge_corpora",
        "knowledge_corpus_revisions",
        ["current_corpus_revision_id"],
        ["corpus_revision_id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_knowledge_corpus_current_snapshot",
        "knowledge_corpora",
        "knowledge_graph_snapshots",
        ["current_graph_snapshot_revision_id"],
        ["graph_snapshot_revision_id"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "knowledge_graph_publications",
        sa.Column("publication_id", sa.String(length=41), nullable=False),
        sa.Column("corpus_id", sa.String(length=39), nullable=False),
        sa.Column("graph_snapshot_revision_id", sa.String(length=41), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_sha256", sa.String(length=71), nullable=False),
        sa.Column("published_by_operator_id", sa.String(length=41), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "request_sha256 ~ '^sha256:[0-9a-f]{64}$'", name="ck_knowledge_graph_publication_hash"
        ),
        sa.ForeignKeyConstraint(
            ["corpus_id"], ["knowledge_corpora.corpus_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["graph_snapshot_revision_id"],
            ["knowledge_graph_snapshots.graph_snapshot_revision_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["published_by_operator_id"], ["operators.operator_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("publication_id"),
        sa.UniqueConstraint(
            "graph_snapshot_revision_id", name="uq_knowledge_graph_publication_snapshot"
        ),
        sa.UniqueConstraint("idempotency_key", name="uq_knowledge_graph_publication_idempotency"),
    )
    op.create_index(
        op.f("ix_knowledge_graph_publications_corpus_id"),
        "knowledge_graph_publications",
        ["corpus_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_nodes",
        sa.Column("graph_snapshot_revision_id", sa.String(length=41), nullable=False),
        sa.Column("node_id", sa.String(length=72), nullable=False),
        sa.Column("node_type", sa.String(length=48), nullable=False),
        sa.Column("stable_key", sa.String(length=192), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("answer_bearing", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["graph_snapshot_revision_id"],
            ["knowledge_graph_snapshots.graph_snapshot_revision_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("graph_snapshot_revision_id", "node_id"),
        sa.UniqueConstraint(
            "graph_snapshot_revision_id", "stable_key", name="uq_knowledge_node_stable_key"
        ),
    )
    op.create_index(
        "ix_knowledge_node_type",
        "knowledge_nodes",
        ["graph_snapshot_revision_id", "node_type"],
        unique=False,
    )
    op.create_table(
        "curriculum_units",
        sa.Column("graph_snapshot_revision_id", sa.String(length=41), nullable=False),
        sa.Column("curriculum_unit_id", sa.String(length=41), nullable=False),
        sa.Column("node_id", sa.String(length=72), nullable=False),
        sa.Column("framework_revision_id", sa.String(length=46), nullable=False),
        sa.Column("parent_unit_id", sa.String(length=41), nullable=True),
        sa.Column("unit_level", sa.String(length=32), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "unit_level IN ('MAJOR','MIDDLE','MINOR','ACHIEVEMENT_STANDARD')",
            name="ck_curriculum_unit_level",
        ),
        sa.CheckConstraint("ordinal >= 1", name="ck_curriculum_unit_ordinal"),
        sa.ForeignKeyConstraint(
            ["graph_snapshot_revision_id", "node_id"],
            ["knowledge_nodes.graph_snapshot_revision_id", "knowledge_nodes.node_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["graph_snapshot_revision_id", "parent_unit_id"],
            ["curriculum_units.graph_snapshot_revision_id", "curriculum_units.curriculum_unit_id"],
            name="fk_curriculum_unit_parent",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("graph_snapshot_revision_id", "curriculum_unit_id"),
        sa.UniqueConstraint(
            "graph_snapshot_revision_id", "node_id", name="uq_curriculum_unit_node"
        ),
    )
    op.create_index(
        "ix_curriculum_unit_framework_level",
        "curriculum_units",
        ["graph_snapshot_revision_id", "framework_revision_id", "unit_level"],
        unique=False,
    )
    op.create_index(
        "uq_curriculum_child_ordinal",
        "curriculum_units",
        ["graph_snapshot_revision_id", "framework_revision_id", "parent_unit_id", "ordinal"],
        unique=True,
        postgresql_where=sa.text("parent_unit_id IS NOT NULL"),
    )
    op.create_index(
        "uq_curriculum_root_ordinal",
        "curriculum_units",
        ["graph_snapshot_revision_id", "framework_revision_id", "ordinal"],
        unique=True,
        postgresql_where=sa.text("parent_unit_id IS NULL"),
    )
    op.create_table(
        "item_element_refs",
        sa.Column("graph_snapshot_revision_id", sa.String(length=41), nullable=False),
        sa.Column("item_revision_id", sa.String(length=40), nullable=False),
        sa.Column("element_kind", sa.String(length=24), nullable=False),
        sa.Column("element_id", sa.String(length=128), nullable=False),
        sa.Column("node_id", sa.String(length=72), nullable=False),
        sa.Column("item_id", sa.String(length=37), nullable=False),
        sa.Column("item_content_artifact_id", sa.String(length=41), nullable=False),
        sa.Column("item_content_artifact_revision_id", sa.String(length=36), nullable=False),
        sa.Column("item_content_sha256", sa.String(length=71), nullable=False),
        sa.Column("schema_ref", sa.String(length=256), nullable=False),
        sa.Column("answer_bearing", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "element_kind IN ('paragraph','table','image','equation',"
            "'statement_set','statement','choice')",
            name="ck_item_element_kind",
        ),
        sa.CheckConstraint(
            "item_content_sha256 ~ '^sha256:[0-9a-f]{64}$'", name="ck_item_element_content_hash"
        ),
        sa.ForeignKeyConstraint(
            ["graph_snapshot_revision_id", "node_id"],
            ["knowledge_nodes.graph_snapshot_revision_id", "knowledge_nodes.node_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_content_artifact_id"],
            ["artifacts.logical_artifact_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["item_content_artifact_revision_id"],
            ["artifact_revisions.revision_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.item_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["item_revision_id"], ["item_revisions.item_revision_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint(
            "graph_snapshot_revision_id", "item_revision_id", "element_kind", "element_id"
        ),
        sa.UniqueConstraint("graph_snapshot_revision_id", "node_id", name="uq_item_element_node"),
    )
    op.create_index(
        "ix_item_element_revision_kind",
        "item_element_refs",
        ["graph_snapshot_revision_id", "item_revision_id", "element_kind"],
        unique=False,
    )
    op.create_index(
        "ix_item_element_reverse",
        "item_element_refs",
        ["item_revision_id", "element_kind", "graph_snapshot_revision_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_edges",
        sa.Column("graph_snapshot_revision_id", sa.String(length=41), nullable=False),
        sa.Column("edge_id", sa.String(length=72), nullable=False),
        sa.Column("edge_type", sa.String(length=48), nullable=False),
        sa.Column("from_node_id", sa.String(length=72), nullable=False),
        sa.Column("to_node_id", sa.String(length=72), nullable=False),
        sa.Column("confidence_milli", sa.Integer(), nullable=False),
        sa.Column("answer_bearing", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "confidence_milli >= 0 AND confidence_milli <= 1000",
            name="ck_knowledge_edge_confidence",
        ),
        sa.CheckConstraint("from_node_id <> to_node_id", name="ck_knowledge_edge_not_self"),
        sa.ForeignKeyConstraint(
            ["graph_snapshot_revision_id", "from_node_id"],
            ["knowledge_nodes.graph_snapshot_revision_id", "knowledge_nodes.node_id"],
            name="fk_knowledge_edge_from_node",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["graph_snapshot_revision_id", "to_node_id"],
            ["knowledge_nodes.graph_snapshot_revision_id", "knowledge_nodes.node_id"],
            name="fk_knowledge_edge_to_node",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("graph_snapshot_revision_id", "edge_id"),
    )
    op.create_index(
        "ix_knowledge_edge_inbound",
        "knowledge_edges",
        ["graph_snapshot_revision_id", "to_node_id", "edge_type"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_edge_outbound",
        "knowledge_edges",
        ["graph_snapshot_revision_id", "from_node_id", "edge_type"],
        unique=False,
    )
    op.create_table(
        "knowledge_node_source_pointers",
        sa.Column("pointer_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("graph_snapshot_revision_id", sa.String(length=41), nullable=False),
        sa.Column("node_id", sa.String(length=72), nullable=False),
        sa.Column("source_revision_id", sa.String(length=50), nullable=False),
        sa.Column("source_class", sa.String(length=32), nullable=False),
        sa.Column("source_artifact_id", sa.String(length=41), nullable=False),
        sa.Column("artifact_revision_id", sa.String(length=36), nullable=False),
        sa.Column("source_sha256", sa.String(length=71), nullable=False),
        sa.Column("member_path", sa.Text(), nullable=False),
        sa.Column("anchor_id", sa.String(length=71), nullable=False),
        sa.Column("excerpt_sha256", sa.String(length=71), nullable=False),
        sa.CheckConstraint(
            "excerpt_sha256 ~ '^sha256:[0-9a-f]{64}$' AND source_sha256 ~ '^sha256:[0-9a-f]{64}$'",
            name="ck_knowledge_node_source_hash",
        ),
        sa.ForeignKeyConstraint(
            ["artifact_revision_id"], ["artifact_revisions.revision_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"], ["artifacts.logical_artifact_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["graph_snapshot_revision_id", "node_id"],
            ["knowledge_nodes.graph_snapshot_revision_id", "knowledge_nodes.node_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pointer_id"),
        sa.UniqueConstraint(
            "graph_snapshot_revision_id",
            "node_id",
            "source_revision_id",
            "artifact_revision_id",
            "member_path",
            "anchor_id",
            name="uq_knowledge_node_source_pointer",
        ),
    )
    op.create_index(
        "ix_knowledge_node_source_class",
        "knowledge_node_source_pointers",
        ["graph_snapshot_revision_id", "source_class", "source_revision_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_node_source_artifact",
        "knowledge_node_source_pointers",
        ["artifact_revision_id", "source_revision_id"],
        unique=False,
    )
    op.create_table(
        "curriculum_unit_closure",
        sa.Column("graph_snapshot_revision_id", sa.String(length=41), nullable=False),
        sa.Column("framework_revision_id", sa.String(length=46), nullable=False),
        sa.Column("ancestor_unit_id", sa.String(length=41), nullable=False),
        sa.Column("descendant_unit_id", sa.String(length=41), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.CheckConstraint("depth >= 0", name="ck_curriculum_closure_depth"),
        sa.ForeignKeyConstraint(
            ["graph_snapshot_revision_id", "ancestor_unit_id"],
            ["curriculum_units.graph_snapshot_revision_id", "curriculum_units.curriculum_unit_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["graph_snapshot_revision_id", "descendant_unit_id"],
            ["curriculum_units.graph_snapshot_revision_id", "curriculum_units.curriculum_unit_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "graph_snapshot_revision_id",
            "framework_revision_id",
            "ancestor_unit_id",
            "descendant_unit_id",
        ),
    )
    op.create_index(
        "ix_curriculum_closure_descendants",
        "curriculum_unit_closure",
        ["graph_snapshot_revision_id", "framework_revision_id", "ancestor_unit_id", "depth"],
        unique=False,
    )
    op.create_index(
        "ix_curriculum_closure_ancestors",
        "curriculum_unit_closure",
        ["graph_snapshot_revision_id", "framework_revision_id", "descendant_unit_id", "depth"],
        unique=False,
    )
    op.create_table(
        "knowledge_edge_source_pointers",
        sa.Column("pointer_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("graph_snapshot_revision_id", sa.String(length=41), nullable=False),
        sa.Column("edge_id", sa.String(length=72), nullable=False),
        sa.Column("source_revision_id", sa.String(length=50), nullable=False),
        sa.Column("source_class", sa.String(length=32), nullable=False),
        sa.Column("source_artifact_id", sa.String(length=41), nullable=False),
        sa.Column("artifact_revision_id", sa.String(length=36), nullable=False),
        sa.Column("source_sha256", sa.String(length=71), nullable=False),
        sa.Column("member_path", sa.Text(), nullable=False),
        sa.Column("anchor_id", sa.String(length=71), nullable=False),
        sa.Column("excerpt_sha256", sa.String(length=71), nullable=False),
        sa.CheckConstraint(
            "excerpt_sha256 ~ '^sha256:[0-9a-f]{64}$' AND source_sha256 ~ '^sha256:[0-9a-f]{64}$'",
            name="ck_knowledge_edge_source_hash",
        ),
        sa.ForeignKeyConstraint(
            ["artifact_revision_id"], ["artifact_revisions.revision_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"], ["artifacts.logical_artifact_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["graph_snapshot_revision_id", "edge_id"],
            ["knowledge_edges.graph_snapshot_revision_id", "knowledge_edges.edge_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pointer_id"),
        sa.UniqueConstraint(
            "graph_snapshot_revision_id",
            "edge_id",
            "source_revision_id",
            "artifact_revision_id",
            "member_path",
            "anchor_id",
            name="uq_knowledge_edge_source_pointer",
        ),
    )
    op.create_index(
        "ix_knowledge_edge_source_class",
        "knowledge_edge_source_pointers",
        ["graph_snapshot_revision_id", "source_class", "source_revision_id"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_edge_source_artifact",
        "knowledge_edge_source_pointers",
        ["artifact_revision_id", "source_revision_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_snapshot_analyses",
        sa.Column("snapshot_analysis_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("graph_snapshot_revision_id", sa.String(length=41), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=44), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_revision_id", sa.String(length=50), nullable=False),
        sa.Column("source_artifact_id", sa.String(length=41), nullable=False),
        sa.Column("source_artifact_revision_id", sa.String(length=36), nullable=False),
        sa.Column("source_sha256", sa.String(length=71), nullable=False),
        sa.Column("accepted_result_artifact_id", sa.String(length=41), nullable=False),
        sa.Column("accepted_result_artifact_revision_id", sa.String(length=36), nullable=False),
        sa.Column("accepted_result_sha256", sa.String(length=71), nullable=False),
        sa.CheckConstraint(
            "accepted_result_sha256 ~ '^sha256:[0-9a-f]{64}$' "
            "AND source_sha256 ~ '^sha256:[0-9a-f]{64}$'",
            name="ck_knowledge_snapshot_analysis_hashes",
        ),
        sa.CheckConstraint(
            "source_kind IN ('CONTENT_INTAKE_FILE','APPROVED_ITEM_REVISION')",
            name="ck_knowledge_snapshot_analysis_source_kind",
        ),
        sa.ForeignKeyConstraint(
            ["accepted_result_artifact_id"],
            ["artifacts.logical_artifact_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["accepted_result_artifact_revision_id"],
            ["artifact_revisions.revision_id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"], ["knowledge_analysis_runs.analysis_run_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["graph_snapshot_revision_id"],
            ["knowledge_graph_snapshots.graph_snapshot_revision_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"], ["artifacts.logical_artifact_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_revision_id"], ["artifact_revisions.revision_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("snapshot_analysis_id"),
        sa.UniqueConstraint(
            "graph_snapshot_revision_id", "analysis_run_id", name="uq_knowledge_snapshot_analysis"
        ),
    )
    op.create_index(
        "ix_knowledge_snapshot_source_revision",
        "knowledge_snapshot_analyses",
        ["source_kind", "source_revision_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_knowledge_snapshot_source_revision", table_name="knowledge_snapshot_analyses")
    op.drop_table("knowledge_snapshot_analyses")
    op.drop_index("ix_knowledge_edge_source_artifact", table_name="knowledge_edge_source_pointers")
    op.drop_index("ix_knowledge_edge_source_class", table_name="knowledge_edge_source_pointers")
    op.drop_table("knowledge_edge_source_pointers")
    op.drop_index("ix_curriculum_closure_descendants", table_name="curriculum_unit_closure")
    op.drop_table("curriculum_unit_closure")
    op.drop_index("ix_knowledge_node_source_artifact", table_name="knowledge_node_source_pointers")
    op.drop_index("ix_knowledge_node_source_class", table_name="knowledge_node_source_pointers")
    op.drop_table("knowledge_node_source_pointers")
    op.drop_index("ix_knowledge_edge_outbound", table_name="knowledge_edges")
    op.drop_index("ix_knowledge_edge_inbound", table_name="knowledge_edges")
    op.drop_table("knowledge_edges")
    op.drop_index("ix_item_element_revision_kind", table_name="item_element_refs")
    op.drop_table("item_element_refs")
    op.drop_index("uq_curriculum_root_ordinal", table_name="curriculum_units")
    op.drop_index("uq_curriculum_child_ordinal", table_name="curriculum_units")
    op.drop_index("ix_curriculum_unit_framework_level", table_name="curriculum_units")
    op.drop_table("curriculum_units")
    op.drop_index("ix_knowledge_node_type", table_name="knowledge_nodes")
    op.drop_table("knowledge_nodes")
    op.drop_index(
        op.f("ix_knowledge_graph_publications_corpus_id"), table_name="knowledge_graph_publications"
    )
    op.drop_table("knowledge_graph_publications")
    op.drop_index(
        op.f("ix_knowledge_graph_snapshots_graph_id"), table_name="knowledge_graph_snapshots"
    )
    op.drop_index("ix_knowledge_graph_snapshot_created", table_name="knowledge_graph_snapshots")
    op.drop_constraint(
        "fk_knowledge_corpus_current_snapshot", "knowledge_corpora", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_knowledge_corpus_current_revision", "knowledge_corpora", type_="foreignkey"
    )
    op.drop_table("knowledge_graph_snapshots")
    op.drop_index(
        op.f("ix_knowledge_corpus_revisions_corpus_id"), table_name="knowledge_corpus_revisions"
    )
    op.drop_table("knowledge_corpus_revisions")
    op.drop_table("knowledge_corpora")
    # ### end Alembic commands ###
