"""add item registry and usage ledger

Revision ID: 20260817_0005
Revises: 20260817_0004
Create Date: 2026-08-17 15:35:17.537013
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260817_0005"
down_revision: str | Sequence[str] | None = "20260817_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deliverables",
        sa.Column("deliverable_id", sa.String(length=44), nullable=False),
        sa.Column("deliverable_key", sa.String(length=128), nullable=False),
        sa.Column("deliverable_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("edition", sa.String(length=64), nullable=False),
        sa.Column("lifecycle_state", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.CheckConstraint(
            "deliverable_type IN ('MOCK_EXAM','TEXTBOOK','WEEKLY','OTHER')",
            name="ck_deliverables_type",
        ),
        sa.CheckConstraint(
            "lifecycle_state IN ('PLANNED','IN_PRODUCTION','RELEASED','CANCELLED','ARCHIVED')",
            name="ck_deliverables_state",
        ),
        sa.PrimaryKeyConstraint("deliverable_id"),
        sa.UniqueConstraint("deliverable_key"),
    )
    op.create_index(
        op.f("ix_deliverables_deliverable_type"), "deliverables", ["deliverable_type"], unique=False
    )
    op.create_table(
        "items",
        sa.Column("item_id", sa.String(length=37), nullable=False),
        sa.Column("human_reference_code", sa.String(length=128), nullable=True),
        sa.Column("lifecycle_state", sa.String(length=32), nullable=False),
        sa.Column("current_revision_id", sa.String(length=40), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retirement_reason", sa.Text(), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "lifecycle_state IN ('DRAFT','ACTIVE','RETIRED','DELETED_SOFT')",
            name="ck_items_lifecycle_state",
        ),
        sa.ForeignKeyConstraint(
            ["current_revision_id"],
            ["item_revisions.item_revision_id"],
            name="fk_items_current_revision",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("item_id"),
        sa.UniqueConstraint("current_revision_id"),
        sa.UniqueConstraint("human_reference_code"),
    )
    op.create_index(op.f("ix_items_lifecycle_state"), "items", ["lifecycle_state"], unique=False)
    op.create_index("ix_items_keyset", "items", ["created_at", "item_id"], unique=False)
    op.create_table(
        "deliverable_revisions",
        sa.Column("deliverable_revision_id", sa.String(length=41), nullable=False),
        sa.Column("deliverable_id", sa.String(length=44), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata_sha256", sa.String(length=71), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("revision_number > 0", name="ck_deliverable_revision_number_positive"),
        sa.ForeignKeyConstraint(
            ["deliverable_id"],
            ["deliverables.deliverable_id"],
        ),
        sa.PrimaryKeyConstraint("deliverable_revision_id"),
        sa.UniqueConstraint(
            "deliverable_id", "revision_number", name="uq_deliverable_revision_number"
        ),
    )
    op.create_index(
        op.f("ix_deliverable_revisions_deliverable_id"),
        "deliverable_revisions",
        ["deliverable_id"],
        unique=False,
    )
    op.create_table(
        "item_relationships",
        sa.Column("item_relationship_id", sa.String(length=45), nullable=False),
        sa.Column("source_item_id", sa.String(length=37), nullable=False),
        sa.Column("target_item_id", sa.String(length=37), nullable=False),
        sa.Column("relationship_type", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_item_id <> target_item_id", name="ck_item_relationship_not_self"
        ),
        sa.ForeignKeyConstraint(
            ["source_item_id"],
            ["items.item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_item_id"],
            ["items.item_id"],
        ),
        sa.PrimaryKeyConstraint("item_relationship_id"),
        sa.UniqueConstraint(
            "source_item_id", "target_item_id", "relationship_type", name="uq_item_relationship"
        ),
    )
    op.create_table(
        "deliverable_events",
        sa.Column("event_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("deliverable_id", sa.String(length=44), nullable=False),
        sa.Column("deliverable_revision_id", sa.String(length=41), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("prior_state", sa.String(length=32), nullable=True),
        sa.Column("new_state", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deliverable_id"], ["deliverables.deliverable_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["deliverable_revision_id"],
            ["deliverable_revisions.deliverable_revision_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("deliverable_id", "sequence", name="uq_deliverable_event_sequence"),
    )
    op.create_index(
        op.f("ix_deliverable_events_deliverable_id"),
        "deliverable_events",
        ["deliverable_id"],
        unique=False,
    )
    op.create_table(
        "item_revisions",
        sa.Column("item_revision_id", sa.String(length=40), nullable=False),
        sa.Column("item_id", sa.String(length=37), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("revision_state", sa.String(length=32), nullable=False),
        sa.Column("registration_key", sa.String(length=200), nullable=False),
        sa.Column("content_pack_release_id", sa.String(length=40), nullable=False),
        sa.Column("workflow_id", sa.String(length=41), nullable=False),
        sa.Column("workflow_definition_version", sa.String(length=32), nullable=False),
        sa.Column("source_workflow_step_run_id", sa.String(length=40), nullable=False),
        sa.Column("manifest_artifact_id", sa.String(length=41), nullable=False),
        sa.Column("manifest_artifact_revision_id", sa.String(length=36), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=71), nullable=False),
        sa.Column("item_type_key", sa.String(length=128), nullable=False),
        sa.Column("primary_taxonomy_ref", sa.String(length=256), nullable=True),
        sa.Column("difficulty_band", sa.String(length=64), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata_sha256", sa.String(length=71), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", sa.String(length=128), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by_revision_id", sa.String(length=40), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "revision_state IN ('DRAFT','IN_REVIEW','APPROVED','REJECTED','SUPERSEDED','RETIRED')",
            name="ck_item_revisions_state",
        ),
        sa.CheckConstraint("revision_number > 0", name="ck_item_revision_number_positive"),
        sa.ForeignKeyConstraint(
            ["content_pack_release_id"],
            ["content_pack_releases.content_pack_release_id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["manifest_artifact_id"],
            ["artifacts.logical_artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["manifest_artifact_revision_id"],
            ["artifact_revisions.revision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_workflow_step_run_id"],
            ["workflow_step_runs.step_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_revision_id"],
            ["item_revisions.item_revision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_instances.workflow_id"],
        ),
        sa.PrimaryKeyConstraint("item_revision_id"),
        sa.UniqueConstraint("item_id", "revision_number", name="uq_item_revision_number"),
        sa.UniqueConstraint("registration_key", name="uq_item_registration_key"),
    )
    op.create_index(
        op.f("ix_item_revisions_content_pack_release_id"),
        "item_revisions",
        ["content_pack_release_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_item_revisions_created_at"), "item_revisions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_item_revisions_difficulty_band"),
        "item_revisions",
        ["difficulty_band"],
        unique=False,
    )
    op.create_index(op.f("ix_item_revisions_item_id"), "item_revisions", ["item_id"], unique=False)
    op.create_index(
        op.f("ix_item_revisions_item_type_key"), "item_revisions", ["item_type_key"], unique=False
    )
    op.create_index(
        op.f("ix_item_revisions_primary_taxonomy_ref"),
        "item_revisions",
        ["primary_taxonomy_ref"],
        unique=False,
    )
    op.create_index(
        op.f("ix_item_revisions_revision_state"), "item_revisions", ["revision_state"], unique=False
    )
    op.create_index(
        op.f("ix_item_revisions_workflow_id"), "item_revisions", ["workflow_id"], unique=False
    )
    op.create_foreign_key(
        "fk_items_current_revision",
        "items",
        "item_revisions",
        ["current_revision_id"],
        ["item_revision_id"],
    )
    op.create_table(
        "item_components",
        sa.Column("item_component_id", sa.String(length=46), nullable=False),
        sa.Column("item_revision_id", sa.String(length=40), nullable=False),
        sa.Column("component_type", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("schema_ref", sa.String(length=256), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("artifact_id", sa.String(length=41), nullable=False),
        sa.Column("artifact_revision_id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=71), nullable=False),
        sa.Column("logical_name", sa.String(length=128), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("ordinal >= 0", name="ck_item_component_ordinal_nonnegative"),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.logical_artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["artifact_revision_id"],
            ["artifact_revisions.revision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_revision_id"], ["item_revisions.item_revision_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("item_component_id"),
        sa.UniqueConstraint(
            "item_revision_id", "component_type", "ordinal", name="uq_item_component_position"
        ),
    )
    op.create_index(
        op.f("ix_item_components_item_revision_id"),
        "item_components",
        ["item_revision_id"],
        unique=False,
    )
    op.create_table(
        "item_events",
        sa.Column("event_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("item_id", sa.String(length=37), nullable=False),
        sa.Column("item_revision_id", sa.String(length=40), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("prior_state", sa.String(length=32), nullable=True),
        sa.Column("new_state", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("command_id", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.item_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["item_revision_id"],
            ["item_revisions.item_revision_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("item_id", "sequence", name="uq_item_event_sequence"),
    )
    op.create_index(op.f("ix_item_events_item_id"), "item_events", ["item_id"], unique=False)
    op.create_table(
        "item_metadata_snapshots",
        sa.Column("item_metadata_snapshot_id", sa.String(length=41), nullable=False),
        sa.Column("item_revision_id", sa.String(length=40), nullable=False),
        sa.Column("schema_ref", sa.String(length=256), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("taxonomy_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tag_keys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("difficulty_band", sa.String(length=64), nullable=False),
        sa.Column("item_type_key", sa.String(length=128), nullable=False),
        sa.Column("estimated_time_seconds", sa.Integer(), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata_sha256", sa.String(length=71), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_revision_id"], ["item_revisions.item_revision_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("item_metadata_snapshot_id"),
        sa.UniqueConstraint("item_revision_id"),
    )
    op.create_table(
        "item_provenance",
        sa.Column("item_provenance_id", sa.String(length=43), nullable=False),
        sa.Column("item_revision_id", sa.String(length=40), nullable=False),
        sa.Column("provenance_type", sa.String(length=32), nullable=False),
        sa.Column("source_key", sa.String(length=128), nullable=False),
        sa.Column("source_reference", sa.String(length=256), nullable=False),
        sa.Column("source_intake_batch_id", sa.String(length=39), nullable=True),
        sa.Column("source_file_id", sa.String(length=43), nullable=True),
        sa.Column("source_artifact_id", sa.String(length=41), nullable=True),
        sa.Column("source_artifact_revision_id", sa.String(length=36), nullable=True),
        sa.Column("source_sha256", sa.String(length=71), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_revision_id"], ["item_revisions.item_revision_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["artifacts.logical_artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_revision_id"],
            ["artifact_revisions.revision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["content_intake_source_files.source_file_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_intake_batch_id"],
            ["content_intake_batches.intake_batch_id"],
        ),
        sa.PrimaryKeyConstraint("item_provenance_id"),
    )
    op.create_index(
        op.f("ix_item_provenance_item_revision_id"),
        "item_provenance",
        ["item_revision_id"],
        unique=False,
    )
    op.create_table(
        "item_review_records",
        sa.Column("item_review_record_id", sa.String(length=43), nullable=False),
        sa.Column("item_revision_id", sa.String(length=40), nullable=False),
        sa.Column("workflow_id", sa.String(length=41), nullable=False),
        sa.Column("review_artifact_id", sa.String(length=41), nullable=False),
        sa.Column("review_artifact_revision_id", sa.String(length=36), nullable=False),
        sa.Column("review_sha256", sa.String(length=71), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("severity_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reviewer_actor_id", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_revision_id"],
            ["item_revisions.item_revision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_artifact_id"],
            ["artifacts.logical_artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_artifact_revision_id"],
            ["artifact_revisions.revision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow_instances.workflow_id"],
        ),
        sa.PrimaryKeyConstraint("item_review_record_id"),
    )
    op.create_index(
        op.f("ix_item_review_records_item_revision_id"),
        "item_review_records",
        ["item_revision_id"],
        unique=False,
    )
    op.create_table(
        "usage_plans",
        sa.Column("usage_plan_id", sa.String(length=42), nullable=False),
        sa.Column("item_id", sa.String(length=37), nullable=False),
        sa.Column("preferred_item_revision_id", sa.String(length=40), nullable=True),
        sa.Column("deliverable_id", sa.String(length=44), nullable=False),
        sa.Column("deliverable_revision_id", sa.String(length=41), nullable=True),
        sa.Column("planned_section", sa.String(length=128), nullable=False),
        sa.Column("planned_sequence", sa.Integer(), nullable=False),
        sa.Column("planned_points", sa.String(length=16), nullable=True),
        sa.Column("planned_role", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.CheckConstraint("planned_sequence > 0", name="ck_usage_plan_sequence_positive"),
        sa.CheckConstraint(
            "status IN ('PLANNED','RESERVED','CANCELLED','FULFILLED')",
            name="ck_usage_plans_status",
        ),
        sa.ForeignKeyConstraint(
            ["deliverable_id"],
            ["deliverables.deliverable_id"],
        ),
        sa.ForeignKeyConstraint(
            ["deliverable_revision_id"],
            ["deliverable_revisions.deliverable_revision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["preferred_item_revision_id"],
            ["item_revisions.item_revision_id"],
        ),
        sa.PrimaryKeyConstraint("usage_plan_id"),
        sa.UniqueConstraint(
            "deliverable_id", "planned_section", "planned_sequence", name="uq_usage_plan_placement"
        ),
    )
    op.create_index(
        op.f("ix_usage_plans_deliverable_id"), "usage_plans", ["deliverable_id"], unique=False
    )
    op.create_index(op.f("ix_usage_plans_item_id"), "usage_plans", ["item_id"], unique=False)
    op.create_index(op.f("ix_usage_plans_status"), "usage_plans", ["status"], unique=False)
    op.create_table(
        "usage_records",
        sa.Column("usage_record_id", sa.String(length=44), nullable=False),
        sa.Column("item_id", sa.String(length=37), nullable=False),
        sa.Column("item_revision_id", sa.String(length=40), nullable=False),
        sa.Column("deliverable_id", sa.String(length=44), nullable=False),
        sa.Column("deliverable_revision_id", sa.String(length=41), nullable=False),
        sa.Column("section", sa.String(length=128), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("points", sa.String(length=16), nullable=True),
        sa.Column("usage_role", sa.String(length=64), nullable=False),
        sa.Column("source_usage_plan_id", sa.String(length=42), nullable=True),
        sa.Column("recorded_by", sa.String(length=128), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("sequence > 0", name="ck_usage_record_sequence_positive"),
        sa.ForeignKeyConstraint(
            ["deliverable_id"],
            ["deliverables.deliverable_id"],
        ),
        sa.ForeignKeyConstraint(
            ["deliverable_revision_id"],
            ["deliverable_revisions.deliverable_revision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_revision_id"],
            ["item_revisions.item_revision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_usage_plan_id"],
            ["usage_plans.usage_plan_id"],
        ),
        sa.PrimaryKeyConstraint("usage_record_id"),
        sa.UniqueConstraint(
            "deliverable_revision_id", "section", "sequence", name="uq_usage_record_placement"
        ),
        sa.UniqueConstraint("source_usage_plan_id"),
    )
    op.create_index(op.f("ix_usage_records_item_id"), "usage_records", ["item_id"], unique=False)
    op.create_index(
        op.f("ix_usage_records_item_revision_id"),
        "usage_records",
        ["item_revision_id"],
        unique=False,
    )
    op.execute(
        """
        CREATE FUNCTION protect_item_revision_payload() RETURNS trigger AS $$
        DECLARE parent_state text;
        BEGIN
          IF TG_TABLE_NAME = 'item_revisions' THEN
            IF TG_OP = 'DELETE' AND OLD.revision_state IN ('APPROVED','SUPERSEDED','RETIRED') THEN
              RAISE EXCEPTION 'approved item revision is immutable';
            END IF;
            IF TG_OP = 'UPDATE' AND OLD.revision_state = 'APPROVED'
              AND NEW.revision_state = 'SUPERSEDED'
              AND NEW.item_id IS NOT DISTINCT FROM OLD.item_id
              AND NEW.revision_number IS NOT DISTINCT FROM OLD.revision_number
              AND NEW.registration_key IS NOT DISTINCT FROM OLD.registration_key
              AND NEW.content_pack_release_id IS NOT DISTINCT FROM OLD.content_pack_release_id
              AND NEW.workflow_id IS NOT DISTINCT FROM OLD.workflow_id
              AND NEW.workflow_definition_version IS NOT DISTINCT FROM
                OLD.workflow_definition_version
              AND NEW.source_workflow_step_run_id IS NOT DISTINCT FROM
                OLD.source_workflow_step_run_id
              AND NEW.manifest_artifact_id IS NOT DISTINCT FROM OLD.manifest_artifact_id
              AND NEW.manifest_artifact_revision_id IS NOT DISTINCT FROM
                OLD.manifest_artifact_revision_id
              AND NEW.manifest_sha256 IS NOT DISTINCT FROM OLD.manifest_sha256
              AND NEW.item_type_key IS NOT DISTINCT FROM OLD.item_type_key
              AND NEW.primary_taxonomy_ref IS NOT DISTINCT FROM OLD.primary_taxonomy_ref
              AND NEW.difficulty_band IS NOT DISTINCT FROM OLD.difficulty_band
              AND NEW.metadata_json IS NOT DISTINCT FROM OLD.metadata_json
              AND NEW.metadata_sha256 IS NOT DISTINCT FROM OLD.metadata_sha256
              AND NEW.created_at IS NOT DISTINCT FROM OLD.created_at
              AND NEW.created_by IS NOT DISTINCT FROM OLD.created_by
              AND NEW.approved_at IS NOT DISTINCT FROM OLD.approved_at
              AND NEW.approved_by IS NOT DISTINCT FROM OLD.approved_by THEN
              RETURN NEW;
            END IF;
            IF TG_OP = 'UPDATE' AND OLD.revision_state IN ('APPROVED','SUPERSEDED','RETIRED') THEN
              RAISE EXCEPTION 'approved item revision is immutable';
            END IF;
            RETURN COALESCE(NEW, OLD);
          END IF;
          SELECT revision_state INTO parent_state FROM item_revisions
            WHERE item_revision_id = OLD.item_revision_id;
          IF parent_state IN ('APPROVED','SUPERSEDED','RETIRED') THEN
            RAISE EXCEPTION 'approved item revision child is immutable';
          END IF;
          RETURN COALESCE(NEW, OLD);
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        "CREATE TRIGGER item_revisions_immutable BEFORE UPDATE OR DELETE ON item_revisions "
        "FOR EACH ROW EXECUTE FUNCTION protect_item_revision_payload()"
    )
    for table in ("item_components", "item_metadata_snapshots", "item_provenance"):
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION protect_item_revision_payload()"
        )
    op.execute(
        """
        CREATE FUNCTION protect_usage_record() RETURNS trigger AS $$
        DECLARE revision_state_value text; revision_item_id text;
        BEGIN
          IF TG_OP IN ('UPDATE','DELETE') THEN
            RAISE EXCEPTION 'usage record is immutable';
          END IF;
          SELECT revision_state, item_id INTO revision_state_value, revision_item_id
            FROM item_revisions WHERE item_revision_id = NEW.item_revision_id;
          IF revision_state_value NOT IN ('APPROVED','SUPERSEDED')
            OR revision_item_id IS DISTINCT FROM NEW.item_id THEN
            RAISE EXCEPTION 'usage item revision is not approved';
          END IF;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        "CREATE TRIGGER usage_records_immutable BEFORE INSERT OR UPDATE OR DELETE ON usage_records "
        "FOR EACH ROW EXECUTE FUNCTION protect_usage_record()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS usage_records_immutable ON usage_records")
    op.execute("DROP FUNCTION IF EXISTS protect_usage_record()")
    for table in ("item_components", "item_metadata_snapshots", "item_provenance"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_immutable ON {table}")
    op.execute("DROP TRIGGER IF EXISTS item_revisions_immutable ON item_revisions")
    op.execute("DROP FUNCTION IF EXISTS protect_item_revision_payload()")
    op.drop_index(op.f("ix_usage_records_item_revision_id"), table_name="usage_records")
    op.drop_index(op.f("ix_usage_records_item_id"), table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index(op.f("ix_usage_plans_status"), table_name="usage_plans")
    op.drop_index(op.f("ix_usage_plans_item_id"), table_name="usage_plans")
    op.drop_index(op.f("ix_usage_plans_deliverable_id"), table_name="usage_plans")
    op.drop_table("usage_plans")
    op.drop_index(op.f("ix_item_review_records_item_revision_id"), table_name="item_review_records")
    op.drop_table("item_review_records")
    op.drop_index(op.f("ix_item_provenance_item_revision_id"), table_name="item_provenance")
    op.drop_table("item_provenance")
    op.drop_table("item_metadata_snapshots")
    op.drop_index(op.f("ix_item_events_item_id"), table_name="item_events")
    op.drop_table("item_events")
    op.drop_index(op.f("ix_item_components_item_revision_id"), table_name="item_components")
    op.drop_table("item_components")
    op.drop_constraint("fk_items_current_revision", "items", type_="foreignkey")
    op.drop_index(op.f("ix_item_revisions_workflow_id"), table_name="item_revisions")
    op.drop_index(op.f("ix_item_revisions_revision_state"), table_name="item_revisions")
    op.drop_index(op.f("ix_item_revisions_primary_taxonomy_ref"), table_name="item_revisions")
    op.drop_index(op.f("ix_item_revisions_item_type_key"), table_name="item_revisions")
    op.drop_index(op.f("ix_item_revisions_item_id"), table_name="item_revisions")
    op.drop_index(op.f("ix_item_revisions_difficulty_band"), table_name="item_revisions")
    op.drop_index(op.f("ix_item_revisions_created_at"), table_name="item_revisions")
    op.drop_index(op.f("ix_item_revisions_content_pack_release_id"), table_name="item_revisions")
    op.drop_table("item_revisions")
    op.drop_index(op.f("ix_deliverable_events_deliverable_id"), table_name="deliverable_events")
    op.drop_table("deliverable_events")
    op.drop_table("item_relationships")
    op.drop_index(
        op.f("ix_deliverable_revisions_deliverable_id"), table_name="deliverable_revisions"
    )
    op.drop_table("deliverable_revisions")
    op.drop_index("ix_items_keyset", table_name="items", if_exists=True)
    op.drop_index(op.f("ix_items_lifecycle_state"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_deliverables_deliverable_type"), table_name="deliverables")
    op.drop_table("deliverables")
    # ### end Alembic commands ###
