"""Machine-readable HWPX failure taxonomy."""

from __future__ import annotations

from enum import StrEnum


class HwpxErrorCode(StrEnum):
    HWPX_REFERENCE_MISSING = "HWPX_REFERENCE_MISSING"
    HWPX_REFERENCE_UNSAFE = "HWPX_REFERENCE_UNSAFE"
    HWPX_REFERENCE_UNSUPPORTED = "HWPX_REFERENCE_UNSUPPORTED"
    HWPX_TEMPLATE_MARKER_MISSING = "HWPX_TEMPLATE_MARKER_MISSING"
    HWPX_TEMPLATE_MARKER_DUPLICATE = "HWPX_TEMPLATE_MARKER_DUPLICATE"
    HWPX_TEMPLATE_BINDING_FAILED = "HWPX_TEMPLATE_BINDING_FAILED"
    HWPX_TEMPLATE_HASH_MISMATCH = "HWPX_TEMPLATE_HASH_MISMATCH"
    HWPX_ZIP_INVALID = "HWPX_ZIP_INVALID"
    HWPX_ZIP_PATH_TRAVERSAL = "HWPX_ZIP_PATH_TRAVERSAL"
    HWPX_ZIP_BOMB_DETECTED = "HWPX_ZIP_BOMB_DETECTED"
    HWPX_ZIP_DUPLICATE_ENTRY = "HWPX_ZIP_DUPLICATE_ENTRY"
    HWPX_MIMETYPE_INVALID = "HWPX_MIMETYPE_INVALID"
    HWPX_XML_INVALID = "HWPX_XML_INVALID"
    HWPX_XML_UNSAFE = "HWPX_XML_UNSAFE"
    HWPX_NAMESPACE_UNSUPPORTED = "HWPX_NAMESPACE_UNSUPPORTED"
    HWPX_MANIFEST_INVALID = "HWPX_MANIFEST_INVALID"
    HWPX_SPINE_INVALID = "HWPX_SPINE_INVALID"
    HWPX_REFERENCE_BROKEN = "HWPX_REFERENCE_BROKEN"
    HWPX_ID_DUPLICATE = "HWPX_ID_DUPLICATE"
    HWPX_TEXT_REPLACEMENT_FAILED = "HWPX_TEXT_REPLACEMENT_FAILED"
    HWPX_TABLE_REPLACEMENT_FAILED = "HWPX_TABLE_REPLACEMENT_FAILED"
    HWPX_IMAGE_BINDING_FAILED = "HWPX_IMAGE_BINDING_FAILED"
    HWPX_IMAGE_REPLACEMENT_FAILED = "HWPX_IMAGE_REPLACEMENT_FAILED"
    HWPX_EQUATION_BINDING_FAILED = "HWPX_EQUATION_BINDING_FAILED"
    HWPX_EQUATION_REPLACEMENT_FAILED = "HWPX_EQUATION_REPLACEMENT_FAILED"
    HWPX_MARKER_REMAINS = "HWPX_MARKER_REMAINS"
    HWPX_PACKAGE_BUILD_FAILED = "HWPX_PACKAGE_BUILD_FAILED"
    HWPX_STRUCTURAL_VALIDATION_FAILED = "HWPX_STRUCTURAL_VALIDATION_FAILED"
    HWPX_SEMANTIC_MISMATCH = "HWPX_SEMANTIC_MISMATCH"
    HWPX_ARTIFACT_COMMIT_FAILED = "HWPX_ARTIFACT_COMMIT_FAILED"
    HWPX_MANUAL_OPEN_FAILED = "HWPX_MANUAL_OPEN_FAILED"
    HWPX_MANUAL_SAVE_FAILED = "HWPX_MANUAL_SAVE_FAILED"
    HWPX_RESAVED_COMPARE_FAILED = "HWPX_RESAVED_COMPARE_FAILED"


class HwpxError(RuntimeError):
    def __init__(self, code: HwpxErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code
