"""Stable HWPX core boundary errors."""

from __future__ import annotations

from enum import StrEnum


class HwpxManagerErrorCode(StrEnum):
    HWPX_REFERENCE_MISSING = "HWPX_REFERENCE_MISSING"
    HWPX_TEMPLATE_HASH_MISMATCH = "HWPX_TEMPLATE_HASH_MISMATCH"
    HWPX_BUILD_NOT_FOUND = "HWPX_BUILD_NOT_FOUND"
    HWPX_BUILD_IDEMPOTENCY_CONFLICT = "HWPX_BUILD_IDEMPOTENCY_CONFLICT"
    HWPX_BUILDER_UNAVAILABLE = "HWPX_BUILDER_UNAVAILABLE"
    HWPX_BUILDER_TIMEOUT = "HWPX_BUILDER_TIMEOUT"
    HWPX_BUILDER_FAILED = "HWPX_BUILDER_FAILED"
    HWPX_RESULT_MISSING = "HWPX_RESULT_MISSING"
    HWPX_RESULT_INVALID = "HWPX_RESULT_INVALID"
    HWPX_STRUCTURAL_VALIDATION_FAILED = "HWPX_STRUCTURAL_VALIDATION_FAILED"
    HWPX_SEMANTIC_MISMATCH = "HWPX_SEMANTIC_MISMATCH"
    HWPX_ARTIFACT_COMMIT_FAILED = "HWPX_ARTIFACT_COMMIT_FAILED"
    HWPX_MANUAL_OPEN_FAILED = "HWPX_MANUAL_OPEN_FAILED"
    HWPX_MANUAL_SAVE_FAILED = "HWPX_MANUAL_SAVE_FAILED"
    HWPX_RESAVED_COMPARE_FAILED = "HWPX_RESAVED_COMPARE_FAILED"
    HWPX_KORDOC_SOURCE_INVALID = "HWPX_KORDOC_SOURCE_INVALID"
    HWPX_KORDOC_RESULT_INVALID = "HWPX_KORDOC_RESULT_INVALID"


class HwpxManagerError(RuntimeError):
    def __init__(self, code: HwpxManagerErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code
