"""Stable Operator identity errors."""

from enum import StrEnum


class IdentityErrorCode(StrEnum):
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_ACCOUNT_LOCKED = "AUTH_ACCOUNT_LOCKED"
    AUTH_PASSWORD_CHANGE_REQUIRED = "AUTH_PASSWORD_CHANGE_REQUIRED"
    AUTH_PASSWORD_POLICY_FAILED = "AUTH_PASSWORD_POLICY_FAILED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_REFRESH_TOKEN_INVALID = "AUTH_REFRESH_TOKEN_INVALID"
    AUTH_REFRESH_TOKEN_REUSED = "AUTH_REFRESH_TOKEN_REUSED"
    AUTH_SESSION_REVOKED = "AUTH_SESSION_REVOKED"
    OPERATOR_NOT_FOUND = "OPERATOR_NOT_FOUND"
    OPERATOR_USERNAME_CONFLICT = "OPERATOR_USERNAME_CONFLICT"
    OPERATOR_DISABLED = "OPERATOR_DISABLED"
    OPERATOR_LAST_ADMIN = "OPERATOR_LAST_ADMIN"
    OPERATOR_ROLE_ALREADY_ASSIGNED = "OPERATOR_ROLE_ALREADY_ASSIGNED"
    OPERATOR_ROLE_NOT_ASSIGNED = "OPERATOR_ROLE_NOT_ASSIGNED"
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND"
    PERMISSION_NOT_FOUND = "PERMISSION_NOT_FOUND"


class IdentityError(RuntimeError):
    def __init__(self, code: IdentityErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code
